# Generated by Django 6.0.2 on 2026-04-26 18:16

import PP.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet_concerne', models.CharField(max_length=20)),
                ('typeDeBesoin', models.CharField(choices=[('Materiel', 'Materiel'), ('Budget', 'Budget'), ('Encadrement', 'Encadrement'), ('Laboratoire', 'Laboratoire'), ('Support Technique', 'Support Technique'), ('Formation', 'Formation'), ('Networking', 'Networking')], default='MATERIEL', max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('justification', models.CharField(max_length=1000)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='files/', validators=[PP.models.Validate_fichier], verbose_name='')),
                ('statut', models.CharField(choices=[('NonVue', 'Non Vue'), ('EnAttente', 'En Attente'), ('Accepte', 'Accepte'), ('Refuse', 'Refuse'), ('DocumentManquant', 'Document Maquant')], default='NonVue', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CompteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField()),
                ('adresse_mail', models.EmailField(max_length=254, validators=[PP.models.Validate_email_adress])),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CompteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricule', models.IntegerField(unique=True, validators=[PP.models.Validate_matricule])),
                ('niveau_etude', models.CharField(choices=[('1CP', '1CP'), ('2CP', '2CP'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], default='1CP', max_length=5)),
                ('adresse_mail', models.EmailField(max_length=254, unique=True, validators=[PP.models.Validate_email_adress])),
                ('telephone', models.IntegerField(validators=[PP.models.Validate_telephone])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('probleme_resolu', models.CharField(max_length=200)),
                ('domaine', models.CharField(choices=[('Technologie et sante', 'Technologie et sante'), ('Technologie et finances', 'Technologie et finances'), ('Technologie et environement', 'Technologie et environement'), ('E-commerce', 'E-commerce'), ('Technologie et agriculture', 'Technologie et agriculture'), ('Autre', 'Autre')], default='Autre', max_length=30)),
                ('objectif', models.CharField(max_length=200)),
                ('file_path', models.FileField(upload_to='files/', validators=[PP.models.Validate_fichier], verbose_name='')),
                ('statut', models.CharField(choices=[('NonVue', 'Non Vue'), ('EnAttente', 'En Attente'), ('Accepte', 'Accepte'), ('Refuse', 'Refuse'), ('DocumentManquant', 'Document Maquant')], default='NonVue', max_length=16)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('contenu', models.CharField(max_length=1500)),
                ('vu', models.BooleanField(default=False)),
                ('emetteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PP.compteadmin')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PP.besoin')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PP.projet')),
                ('receveur', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='besoin',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
