# Generated by Django 6.0.2 on 2026-04-26 18:19

import PP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteetudiant',
            name='adresse_mail',
            field=models.EmailField(default='Bonjour@estin.dz', max_length=254, unique=True, validators=[PP.models.Validate_email_adress]),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(default='121241212', unique=True, validators=[PP.models.Validate_matricule]),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='telephone',
            field=models.IntegerField(default=42, validators=[PP.models.Validate_telephone]),
        ),
    ]
