# Generated by Django 6.0.2 on 2026-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0002_alter_compteetudiant_adresse_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteetudiant',
            name='adresse_mail',
            field=models.EmailField(blank=True, default='Bonjour@estin.dz', max_length=254, verbose_name='email address'),
        ),
    ]
