# Generated by Django 6.0.2 on 2026-04-26 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0003_alter_compteetudiant_adresse_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='participants',
        ),
        migrations.AddField(
            model_name='projet',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
