# Generated by Django 6.0.2 on 2026-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0004_remove_projet_participants_projet_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='priority',
            field=models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Elevee', 'Eleve')], default='Elevee', max_length=50),
        ),
    ]
