# Generated by Django 6.0.2 on 2026-04-28 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0005_besoin_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
