# Generated by Django 6.0.2 on 2026-04-28 20:02

import PP.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0006_alter_besoin_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(default='123489357', unique=True, validators=[PP.models.Validate_matricule]),
        ),
    ]
