# Generated by Django 6.0.2 on 2026-04-28 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0008_message_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emetteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='message',
            name='receveur',
        ),
        migrations.DeleteModel(
            name='message_etudiant',
        ),
        migrations.AddField(
            model_name='message',
            name='receveur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recu', to=settings.AUTH_USER_MODEL),
        ),
    ]
