# Generated by Django 6.0.2 on 2026-04-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0009_alter_message_emetteur_remove_message_receveur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='objet',
        ),
    ]
