# Generated by Django 6.0.2 on 2026-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0011_contact_created_at_message_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompteAdmin',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.AlterField(
            model_name='besoin',
            name='projet_concerne',
            field=models.CharField(max_length=100),
        ),
    ]
