# Generated by Django 6.0.2 on 2026-05-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0012_delete_compteadmin_delete_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteetudiant',
            name='adresse_mail',
        ),
    ]
