# Generated by Django 6.0.2 on 2026-05-16 17:19

import PP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0013_remove_compteetudiant_adresse_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(default='123889357', unique=True, validators=[PP.models.Validate_matricule]),
        ),
    ]
