# Generated by Django 6.0.2 on 2026-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0014_alter_compteetudiant_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='equipe',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='statut',
            field=models.CharField(choices=[('NonVue', 'Non vu'), ('EnAttente', 'En attente'), ('Accepte', 'Accepté'), ('Refuse', 'Refusé'), ('DocumentManquant', 'Document manquant')], default='NonVue', max_length=16),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('NonVue', 'Non vu'), ('EnAttente', 'En attente'), ('Accepte', 'Accepté'), ('Refuse', 'Refusé'), ('DocumentManquant', 'Document manquant')], default='NonVue', max_length=16),
        ),
    ]
