# Generated by Django 6.0.2 on 2026-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0015_projet_equipe_alter_besoin_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='statut',
            field=models.CharField(choices=[('Non vu', 'NonVue'), ('En attente', 'EnAttente'), ('Accepté', 'Accepte'), ('Refusé', 'Refuse'), ('Document manquant', 'DocumentManquant')], default='NonVue', max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('Non vu', 'NonVue'), ('En attente', 'EnAttente'), ('Accepté', 'Accepte'), ('Refusé', 'Refuse'), ('Document manquant', 'DocumentManquant')], default='NonVue', max_length=20),
        ),
    ]
