# Generated by Django 6.0.2 on 2026-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0016_alter_besoin_statut_alter_projet_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='equipe',
            field=models.TextField(blank=True),
        ),
    ]
