# Generated by Django 6.0.2 on 2026-05-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0017_alter_projet_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='statut',
            field=models.CharField(choices=[('Non vu', 'Non vu'), ('En attente', 'En attente'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Document manquant', 'Document manquant')], default='NonVue', max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('Non vu', 'Non vu'), ('En attente', 'En attente'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Document manquant', 'Document manquant')], default='NonVue', max_length=20),
        ),
    ]
