# Generated by Django 6.0.2 on 2026-05-22 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0018_alter_besoin_statut_alter_projet_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
