# Generated by Django 6.0.2 on 2026-05-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0019_besoin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='statut',
            field=models.CharField(choices=[('Nonvue', 'Non vu'), ('EnAttente', 'En attente'), ('Accepte', 'Accepté'), ('Refuse', 'Refusé'), ('DocumentManquant', 'Document manquant')], default='NonVue', max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('Nonvue', 'Non vu'), ('EnAttente', 'En attente'), ('Accepte', 'Accepté'), ('Refuse', 'Refusé'), ('DocumentManquant', 'Document manquant')], default='NonVue', max_length=20),
        ),
    ]
