# Generated by Django 6.0.2 on 2026-05-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0021_alter_besoin_statut_alter_projet_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='statut',
            field=models.CharField(choices=[('NonVue', 'Non Vue'), ('EnAttente', 'En Attente'), ('Accepte', 'Accepte'), ('Refuse', 'Refuse'), ('DocumentManquant', 'Document Maquant')], default='NonVue', max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('NonVue', 'Non Vue'), ('EnAttente', 'En Attente'), ('Accepte', 'Accepte'), ('Refuse', 'Refuse'), ('DocumentManquant', 'Document Maquant')], default='NonVue', max_length=20),
        ),
    ]
